version: '3.8'

services:
  postgres:
    image: postgres:16.9-bookworm
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  backend:
    build:
      context: ./
    env_file:
      - .env
    environment:
      POSTGRES_DSN: postgresql+asyncpg://postgres_user:postgres_password@postgres:5432/postgres_db
      REDIS_DSN: redis://redis:6379/0
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./src:/opt/app/src/
      - ./pyproject.toml:/opt/app/pyproject.toml
      - ./uv.lock:/opt/app/uv.lock
    command: "fastapi dev main.py --port 80 --host 0.0.0.0"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.4-bookworm
    ports:
      - 6379:6379

volumes:
  postgres_data_test:
